CREATE TABLE Student
(
    ID               INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME         VARCHAR(250) NOT NULL,
    PASSWORD         VARCHAR(250) NOT NULL,
    SECURITYQUESTION VARCHAR(250) NOT NULL,
    SECURITYANSWER   VARCHAR(250) NOT NULL,
    EMAIL            VARCHAR(250) NOT NULL,
    PHONE            VARCHAR(250) NOT NULL
);

INSERT INTO Student (ID, USERNAME, PASSWORD, SECURITYQUESTION, SECURITYANSWER, EMAIL, PHONE)
VALUES (1, 'Test', 'Test@1234', 'favouritecolour', 'RED', 'test@gmal.com', '9812345678');